export const ProfileObject = [
    {
      'id': 'OQyRttOV418',
      'user_name': 'John Doe',
      'user_url': 'https://unsplash.com/@johndoe?utm_source=unsample',
      'photo_url': 'https://unsplash.com/photos/OQyRttOV418?utm_source=unsample',
      'email': 'john.doe@example.com',
      'phone' : '06 20 123 4567',
      'avatar': 'J',
    },
    {
      'id': '5XP-n_Xqqv8',
      'user_name': 'Jane Smith',
      'user_url': 'https://unsplash.com/@janesmith?utm_source=unsample',
      'photo_url': 'https://unsplash.com/photos/5XP-n_Xqqv8?utm_source=unsample',
      'email': 'jane.smith@example.com',
      'phone' : '06 30 987 6543', 
      'avatar': 'J',
    },
    {
      'id': 'Shf_B7x8qDA',
      'user_name': 'Robert Johnson',
      'user_url': 'https://unsplash.com/@robertj?utm_source=unsample',
      'photo_url': 'https://unsplash.com/photos/Shf_B7x8qDA?utm_source=unsample',
      'email': 'robert.j@example.com',
      'phone' : '06 70 246 8135',
      'avatar': 'R',
    },
    {
      'id':'LFAhbzmvpak',
      'user_name': 'Sarah Wilson',
      'user_url': 'https://unsplash.com/@sarahwilson?utm_source=unsample',
      'photo_url': 'https://unsplash.com/photos/LFAhbzmvpak?utm_source=unsample',
      'email': 's.wilson@example.com',
      'phone' : '06 1 555 7788',
      'avatar': 'S',
    },
  {
      'id': 'eFXho78pQH8',
      'user_name': 'Michael Brown',
      'user_url': 'https://unsplash.com/@michaelb?utm_source=unsample',
      'photo_url': 'https://unsplash.com/photos/eFXho78pQH8?utm_source=unsample',
      'email': 'm.brown@example.com',
      'phone' : '06 21 334 2211',
      'avatar': 'M',
    }
];